# CONFIGURACIÓN ESENCIAL DE ANDROIDX (Soluciona la falla de CI/CD #66)
android.useAndroidX=true
android.enableJetifier=false

# OPTIMIZACIÓN DE COMPILACIÓN PARA EL ENTORNO DE GRADLE
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
