# CONFIGURACIÓN ESENCIAL DE ANDROIDX
android.useAndroidX=true
android.enableJetifier=false

# OPTIMIZACIÓN DE COMPILACIÓN (Ajustado para evitar problemas en Gradle 9+)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true

# Desactivamos esto para que el plugin de Kotlin no rompa la compilación en CI
org.gradle.configuration-cache=false
